@startuml

title __MAPPER's Class Diagram__\n

  namespace com.bomvizinho.microservice {
    namespace boundary.controller {
      namespace dto.request {
        namespace mapper {
          class com.bomvizinho.microservice.boundary.controller.dto.request.mapper.IdosoRequestDTOMapper {
              {static} + toIdosoEntity()
          }
        }
      }
    }
  }
  

  namespace com.bomvizinho.microservice {
    namespace boundary.controller {
      namespace dto.request {
        namespace mapper {
          class com.bomvizinho.microservice.boundary.controller.dto.request.mapper.ServicoRequestDTOMapper {
              {static} + toServicoEntity()
          }
        }
      }
    }
  }
  

  namespace com.bomvizinho.microservice {
    namespace boundary.controller {
      namespace dto.request {
        namespace mapper {
          class com.bomvizinho.microservice.boundary.controller.dto.request.mapper.ServicoVoluntarioRequestDTOMapper {
              {static} + toServicoEntity()
          }
        }
      }
    }
  }
  

  namespace com.bomvizinho.microservice {
    namespace boundary.controller {
      namespace dto.request {
        namespace mapper {
          class com.bomvizinho.microservice.boundary.controller.dto.request.mapper.UsuarioRequestDTOMapper {
              {static} + toUsuarioEntity()
          }
        }
      }
    }
  }
  

  namespace com.bomvizinho.microservice {
    namespace boundary.controller {
      namespace dto.request {
        namespace mapper {
          class com.bomvizinho.microservice.boundary.controller.dto.request.mapper.VoluntarioRequestDTOMapper {
              {static} + toVoluntarioEntity()
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
