@startuml

title __EXCEPTION's Class Diagram__\n

  namespace com.bomvizinho.microservice {
    namespace application.exception {
      class com.bomvizinho.microservice.application.exception.AlterarIdosoException {
          + AlterarIdosoException()
      }
    }
  }
  

  namespace com.bomvizinho.microservice {
    namespace application.exception {
      class com.bomvizinho.microservice.application.exception.AlterarSenhaException {
          + AlterarSenhaException()
      }
    }
  }
  

  namespace com.bomvizinho.microservice {
    namespace application.exception {
      class com.bomvizinho.microservice.application.exception.AlterarServicoException {
          + AlterarServicoException()
      }
    }
  }
  

  namespace com.bomvizinho.microservice {
    namespace application.exception {
      class com.bomvizinho.microservice.application.exception.AlterarVoluntarioException {
          + AlterarVoluntarioException()
      }
    }
  }
  

  namespace com.bomvizinho.microservice {
    namespace application.exception {
      class com.bomvizinho.microservice.application.exception.BuscarIdosoException {
          + BuscarIdosoException()
      }
    }
  }
  

  namespace com.bomvizinho.microservice {
    namespace application.exception {
      class com.bomvizinho.microservice.application.exception.BuscarServicoException {
          + BuscarServicoException()
      }
    }
  }
  

  namespace com.bomvizinho.microservice {
    namespace application.exception {
      class com.bomvizinho.microservice.application.exception.BuscarUsuarioException {
          + BuscarUsuarioException()
      }
    }
  }
  

  namespace com.bomvizinho.microservice {
    namespace application.exception {
      class com.bomvizinho.microservice.application.exception.BuscarVoluntarioException {
          + BuscarVoluntarioException()
      }
    }
  }
  

  namespace com.bomvizinho.microservice {
    namespace application.exception {
      class com.bomvizinho.microservice.application.exception.CadastrarUsuarioException {
          + CadastrarUsuarioException()
      }
    }
  }
  

  namespace com.bomvizinho.microservice {
    namespace application.exception {
      class com.bomvizinho.microservice.application.exception.CriarOuAlterarIdosoException {
          + CriarOuAlterarIdosoException()
      }
    }
  }
  

  namespace com.bomvizinho.microservice {
    namespace application.exception {
      class com.bomvizinho.microservice.application.exception.CriarOuAlterarServicoException {
          + CriarOuAlterarServicoException()
      }
    }
  }
  

  namespace com.bomvizinho.microservice {
    namespace application.exception {
      class com.bomvizinho.microservice.application.exception.CriarOuAlterarUsuarioException {
          + CriarOuAlterarUsuarioException()
      }
    }
  }
  

  namespace com.bomvizinho.microservice {
    namespace application.exception {
      class com.bomvizinho.microservice.application.exception.CriarOuAlterarVoluntarioException {
          + CriarOuAlterarVoluntarioException()
      }
    }
  }
  

  namespace com.bomvizinho.microservice {
    namespace application.exception {
      class com.bomvizinho.microservice.application.exception.CriarServicoException {
          + CriarServicoException()
      }
    }
  }
  

  namespace com.bomvizinho.microservice {
    namespace application.exception {
      class com.bomvizinho.microservice.application.exception.DeletarServicoException {
          + DeletarServicoException()
      }
    }
  }
  

  namespace com.bomvizinho.microservice {
    namespace application.exception {
      class com.bomvizinho.microservice.application.exception.LoginException {
          + LoginException()
      }
    }
  }
  

  namespace com.bomvizinho.microservice {
    namespace application.exception {
      class com.bomvizinho.microservice.application.exception.ManterServicoException {
          + ManterServicoException()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
