@startuml

title __ENTITY's Class Diagram__\n

  namespace com.bomvizinho.microservice {
    namespace infrastructure.dataprovider.entity {
      class com.bomvizinho.microservice.infrastructure.dataprovider.entity.Idoso {
          - assistenciaRequerida : String
          - condicaoSaude : String
          - id : Long
          - preferenciaDia : String
          {static} - serialVersionUID : long
          - servicoIdoso : List<Servico>
          + getAssistenciaRequerida()
          + getCondicaoSaude()
          + getId()
          + getPreferenciaDia()
          + getServicoIdoso()
          + getUsuarioIdoso()
          + setAssistenciaRequerida()
          + setCondicaoSaude()
          + setId()
          + setPreferenciaDia()
          + setServicoIdoso()
          + setUsuarioIdoso()
      }
    }
  }
  

  namespace com.bomvizinho.microservice {
    namespace infrastructure.dataprovider.entity {
      class com.bomvizinho.microservice.infrastructure.dataprovider.entity.Servico {
          - dataFim : Timestamp
          - dataInicio : Timestamp
          - destino : String
          - id : Long
          - ordem : String
          {static} - serialVersionUID : long
          - status : String
          + getDataFim()
          + getDataInicio()
          + getDestino()
          + getId()
          + getIdosoServico()
          + getOrdem()
          + getStatus()
          + getVoluntarioServico()
          + setDataFim()
          + setDataInicio()
          + setDestino()
          + setId()
          + setIdosoServico()
          + setOrdem()
          + setStatus()
          + setVoluntarioServico()
      }
    }
  }
  

  namespace com.bomvizinho.microservice {
    namespace infrastructure.dataprovider.entity {
      class com.bomvizinho.microservice.infrastructure.dataprovider.entity.Usuario {
          - bloco : String
          - dataNascimento : Date
          - disponibilidade : String
          - email : String
          - endereco : String
          - id : Long
          - nome : String
          - numeroAp : String
          - senha : String
          {static} - serialVersionUID : long
          - telefone : String
          - tipoPerfil : String
          + getBloco()
          + getDataNascimento()
          + getDisponibilidade()
          + getEmail()
          + getEndereco()
          + getId()
          + getNome()
          + getNumeroAp()
          + getSenha()
          + getTelefone()
          + getTipoPerfil()
          + setBloco()
          + setDataNascimento()
          + setDisponibilidade()
          + setEmail()
          + setEndereco()
          + setId()
          + setNome()
          + setNumeroAp()
          + setSenha()
          + setTelefone()
          + setTipoPerfil()
      }
    }
  }
  

  namespace com.bomvizinho.microservice {
    namespace infrastructure.dataprovider.entity {
      class com.bomvizinho.microservice.infrastructure.dataprovider.entity.Voluntario {
          - habilidade : String
          - id : Long
          - preferencia : String
          {static} - serialVersionUID : long
          - servicoVoluntario : List<Servico>
          + getHabilidade()
          + getId()
          + getPreferencia()
          + getServicoVoluntario()
          + getUsuarioVoluntario()
          + setHabilidade()
          + setId()
          + setPreferencia()
          + setServicoVoluntario()
          + setUsuarioVoluntario()
      }
    }
  }
  

  com.bomvizinho.microservice.infrastructure.dataprovider.entity.Idoso .up.|> java.io.Serializable
  com.bomvizinho.microservice.infrastructure.dataprovider.entity.Idoso o-- com.bomvizinho.microservice.infrastructure.dataprovider.entity.Usuario : usuarioIdoso
  com.bomvizinho.microservice.infrastructure.dataprovider.entity.Servico .up.|> java.io.Serializable
  com.bomvizinho.microservice.infrastructure.dataprovider.entity.Servico o-- com.bomvizinho.microservice.infrastructure.dataprovider.entity.Idoso : idosoServico
  com.bomvizinho.microservice.infrastructure.dataprovider.entity.Servico o-- com.bomvizinho.microservice.infrastructure.dataprovider.entity.Voluntario : voluntarioServico
  com.bomvizinho.microservice.infrastructure.dataprovider.entity.Usuario .up.|> java.io.Serializable
  com.bomvizinho.microservice.infrastructure.dataprovider.entity.Voluntario .up.|> java.io.Serializable
  com.bomvizinho.microservice.infrastructure.dataprovider.entity.Voluntario o-- com.bomvizinho.microservice.infrastructure.dataprovider.entity.Usuario : usuarioVoluntario


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
