@startuml

title __EXCEPTION's Class Diagram__\n

  namespace com.bomvizinho.microservice {
    namespace infrastructure.exception {
      class com.bomvizinho.microservice.infrastructure.exception.SistemaVoluntariadoExceptionHandler {
          + handleAlterarIdosoException()
          + handleAlterarSenhaException()
          + handleAlterarVoluntarioException()
          + handleBuscarIdosoException()
          + handleBuscarServicoException()
          + handleBuscarUsuarioException()
          + handleBuscarVoluntarioException()
          + handleCadastrarUsuarioException()
          + handleCriarOuAlterarIdosoException()
          + handleCriarOuAlterarServicoException()
          + handleCriarOuAlterarVoluntarioException()
          + handleCriarServicoException()
          + handleCriarUsuarioException()
          + handleDeletarServicoException()
          + handleLoginException()
          + handleManterServicoException()
      }
    }
  }
  

  namespace com.bomvizinho.microservice {
    namespace infrastructure.exception {
      class com.bomvizinho.microservice.infrastructure.exception.SistemaVoluntariadoExceptionHandler.Error {
          - exception : String
          - message : String
          + Error()
          + getException()
          + getMessage()
      }
    }
  }
  

  com.bomvizinho.microservice.infrastructure.exception.SistemaVoluntariadoExceptionHandler -up-|> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler
  com.bomvizinho.microservice.infrastructure.exception.SistemaVoluntariadoExceptionHandler +-down- com.bomvizinho.microservice.infrastructure.exception.SistemaVoluntariadoExceptionHandler.Error


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
