@startuml

title __VOLUNTARIO's Class Diagram__\n

  namespace com.bomvizinho.microservice {
    namespace boundary.controller {
      namespace dto.servico {
        namespace voluntario {
          class com.bomvizinho.microservice.boundary.controller.dto.servico.voluntario.VoluntarioDTO {
              - cep : String
              - dataNascimento : String
              - email : String
              - endereco : String
              - nome : String
              - senha : String
              - sobrenome : String
              - telefone : String
              - usuario : String
              + VoluntarioDTO()
              + VoluntarioDTO()
              + getCep()
              + getDataNascimento()
              + getEmail()
              + getEndereco()
              + getNome()
              + getSenha()
              + getSobrenome()
              + getTelefone()
              + getUsuario()
              + setCep()
              + setDataNascimento()
              + setEmail()
              + setEndereco()
              + setNome()
              + setSenha()
              + setSobrenome()
              + setTelefone()
              + setUsuario()
          }
        }
      }
    }
  }
  

  namespace com.bomvizinho.microservice {
    namespace boundary.controller {
      namespace dto.servico {
        namespace voluntario {
          class com.bomvizinho.microservice.boundary.controller.dto.servico.voluntario.VoluntarioDTO.Builder {
              - cep : String
              - dataNascimento : String
              - email : String
              - endereco : String
              - nome : String
              - senha : String
              - sobrenome : String
              - telefone : String
              - usuario : String
              {static} + aVoluntarioDTO()
              + build()
              + withCep()
              + withDataNascimento()
              + withEmail()
              + withEndereco()
              + withNome()
              + withSenha()
              + withSobrenome()
              + withTelefone()
              + withUsuario()
              - Builder()
          }
        }
      }
    }
  }
  

  com.bomvizinho.microservice.boundary.controller.dto.servico.voluntario.VoluntarioDTO +-down- com.bomvizinho.microservice.boundary.controller.dto.servico.voluntario.VoluntarioDTO.Builder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
