@startuml

title __LOGIN's Class Diagram__\n

  namespace com.bomvizinho.microservice {
    namespace boundary.controller {
      namespace dto.login {
        class com.bomvizinho.microservice.boundary.controller.dto.login.UsuarioDTO {
            - cep : String
            - dataNascimento : String
            - email : String
            - endereco : String
            - nome : String
            - perfil : String
            - senha : String
            - telefone : String
            - usuario : String
            + UsuarioDTO()
            + UsuarioDTO()
            + getCep()
            + getDataNascimento()
            + getEmail()
            + getEndereco()
            + getNome()
            + getPerfil()
            + getSenha()
            + getTelefone()
            + getUsuario()
            + setCep()
            + setDataNascimento()
            + setEmail()
            + setEndereco()
            + setNome()
            + setPerfil()
            + setSenha()
            + setTelefone()
            + setUsuario()
        }
      }
    }
  }
  

  namespace com.bomvizinho.microservice {
    namespace boundary.controller {
      namespace dto.login {
        class com.bomvizinho.microservice.boundary.controller.dto.login.UsuarioDTO.Builder {
            - cep : String
            - dataNascimento : String
            - email : String
            - endereco : String
            - nome : String
            - perfil : String
            - senha : String
            - telefone : String
            - usuario : String
            {static} + anUsuarioDTO()
            + build()
            + withCep()
            + withDataNascimento()
            + withEmail()
            + withEndereco()
            + withNome()
            + withPerfil()
            + withSenha()
            + withTelefone()
            + withUsuario()
            - Builder()
        }
      }
    }
  }
  

  com.bomvizinho.microservice.boundary.controller.dto.login.UsuarioDTO +-down- com.bomvizinho.microservice.boundary.controller.dto.login.UsuarioDTO.Builder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
